version: '3.8'

services:
  keycloak:
    build: 
      context: .
    privileged: true
    volumes:
      - ./data/scripts/debug.sh:/opt/keycloak/bin/debug.sh
      # - ./data/providers/keycloak-discord-0.5.0.jar:/opt/keycloak/providers/keycloak-discord-0.5.0.jar # SPI を追加する場合こんなイメージで追加する
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - 8080:8080
      - 5005:5005
    entrypoint: "/opt/keycloak/bin/debug.sh start-dev --debug"
